name: Docker Publish

on:
  push:
    branches: [ main ]
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v1.0.0)'
        required: true
        default: 'latest'

env:
  IMAGE_NAME: jiahaoxyz/facial_recognition_with_rust

jobs:
  docker-publish:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout 仓库
      - name: Checkout
        uses: actions/checkout@v3

      # 2️⃣ 设置 Docker Buildx（支持 multi-arch）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3️⃣ 登录 Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.JIAHAOXYZ }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4️⃣ 提取版本号
      - name: Extract version tag
        id: meta
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          elif [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          else
            echo "VERSION=latest" >> $GITHUB_ENV

      # 5️⃣ 安装系统依赖（Rust + OpenCV 构建）
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            pkg-config \
            libclang-dev \
            libopencv-dev \
            libgtk-3-dev \
            libopenblas-dev \
            liblapack-dev

      # 6️⃣ 构建并推送 Docker 镜像（multi-arch）
      - name: Build and push multi-arch Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.VERSION }}
            ${{ env.IMAGE_NAME }}:latest
          platforms: linux/amd64,linux/arm64
