name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          pkg-config \
          libclang-dev \
          libopencv-dev \
          libgtk-3-dev \
          libopenblas-dev \
          liblapack-dev
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
    
    - name: Cache Cargo registry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Wait for MongoDB to be ready
      run: |
        until docker exec $(docker ps -q) mongosh --eval "print(\"waited for connection\")"
        do
            sleep 2
        done
    
    - name: Run unit tests
      run: cargo test --lib --verbose
      env:
        MONGODB_URI: mongodb://localhost:27017
      
    - name: Run integration tests
      run: cargo test --test integration_test --verbose
      env:
        MONGODB_URI: mongodb://localhost:27017

  build-and-test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          pkg-config \
          libclang-dev \
          libopencv-dev \
          libgtk-3-dev \
          libopenblas-dev \
          liblapack-dev
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
    
    - name: Cache Cargo registry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Wait for MongoDB to be ready
      run: |
        until docker exec $(docker ps -q) mongosh --eval "print(\"waited for connection\")"
        do
            sleep 2
        done
    
    - name: Build
      run: cargo build --verbose
    
    - name: Run all tests
      run: cargo test --verbose
      env:
        MONGODB_URI: mongodb://localhost:27017
      
    - name: Run Clippy
      run: |
        rustup component add clippy
        cargo clippy -- -D warnings
        
    - name: Check formatting
      run: |
        rustup component add rustfmt
        cargo fmt -- --check