name: Scheduled Tests

on:
  schedule:
    # Runs "At 00:00 on Sunday" (see https://crontab.guru)
    - cron: '0 0 * * 0'

jobs:
  scheduled_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable

    - name: Cache Cargo registry and build artifacts
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-scheduled-${{ hashFiles('**/Cargo.lock') }}

    - name: Run tests
      run: cargo test --verbose